# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.1'

gem 'rake'
gem 'rspec'
gem 'capybara'
gem 'poltergeist'
gem 'faraday'
gem 'vcr'
